version: "3.9"
services:

  cloudarch:
    build: ./cloudarch/
    ports:
      - "4200:4200"
    links:
      - api  
  api:
    build: ./api/
    ports:
      - "8080:8080"
    links:
      - database
  
  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jhony
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db 
volumes:
  mongo-data: